[package]
name = "media_player"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rodio = "0.14.0"
getopts = "0.2.21"
rand = "0.5.5"
